services:
  nginx:
    image: nginx:1.27.2
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  signal:
    image: maksimowiczm/zebra-signal-server:latest
    build: server
    environment:
      - RUST_LOG=INFO
  web:
    image: maksimowiczm/zebra-signal-web:latest
    build: web
