services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  signal:
    build: server
    environment:
      - RUST_LOG=INFO
  web:
    build: web
