name: Push web image to Docker Hub

on:
  push:
    branches: ["main"]
    paths: ["web/**"]
  workflow_dispatch:

env:
  IMAGE_NAME_WEB: maksimowiczm/zebra-signal-web

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME_WEB }}
          tags: |
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Login to Docker Hub registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_REGISTRY_TOKEN }}

      - name: Docker build
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./web
          target: production
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
